# Generated by Django 4.2.11 on 2024-05-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('id',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.RemoveField(
            model_name='like',
            name='quantity',
        ),
    ]
