# Generated by Django 4.2.11 on 2024-05-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('author_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(default=0, max_length=6, verbose_name='Цена')),
                ('discount', models.PositiveIntegerField(default=0, max_length=6, null=True, verbose_name='Скидка в %')),
                ('quantity', models.PositiveIntegerField(default=0, max_length=6, null=True, verbose_name='Количество')),
                ('age', models.PositiveIntegerField(default=0, max_length=6, null=True, verbose_name='Возраст')),
                ('year_of_publish', models.PositiveIntegerField(max_length=4, null=True, verbose_name='Год издания')),
                ('publisher', models.CharField(max_length=150, null=True, verbose_name='Издательство')),
                ('cycle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Цикл')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
                'ordering': ('id',),
            },
        ),
    ]
