# Generated by Django 4.2.11 on 2024-04-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='age',
            field=models.PositiveIntegerField(default=0, max_length=6, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='products',
            name='author_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.PositiveIntegerField(default=0, max_length=6, null=True, verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(default=0, max_length=6, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='products',
            name='year_of_publish',
            field=models.PositiveIntegerField(max_length=4, null=True, verbose_name='Год издания'),
        ),
    ]
