# Generated by Django 4.2.11 on 2024-04-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_products_age_alter_products_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='publisher',
            field=models.CharField(max_length=150, null=True, verbose_name='Издательство'),
        ),
    ]
