# Generated by Django 4.2.11 on 2024-04-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cycle',
            field=models.CharField(max_length=150, null=True, verbose_name='Цикл'),
        ),
    ]
