# Generated by Django 4.2.11 on 2024-04-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_products_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cycle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Цикл'),
        ),
    ]
