# Generated by Django 4.2.11 on 2024-05-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_comment_order_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Имя получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Фамилия получателя'),
        ),
    ]
