# Generated by Django 4.2.11 on 2024-05-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='author_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default=None, max_length=150, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Цена'),
        ),
    ]
