# Generated by Django 4.2.11 on 2024-06-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_author_name_orderitem_image_orderitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, null=True, verbose_name='Трек-код'),
        ),
    ]
